In [1]:
from PIL import Image
import numpy as np

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
data[256, 256] = [255, 0, 0]
img = Image.fromarray(data, 'RGB')
# img.save('my.png')
# img.show()

In [2]:
type(data)

numpy.ndarray

In [101]:
from numpy import genfromtxt
# all_data = genfromtxt('5Images.csv', delimiter=',')
all_data = genfromtxt('Dataset1/csvData/sign_mnist_train.csv', delimiter=',')

In [102]:
all_data

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [  3., 107., 118., ..., 204., 203., 202.],
       [  6., 155., 157., ..., 103., 135., 149.],
       ...,
       [ 18., 174., 174., ..., 202., 200., 200.],
       [ 17., 177., 181., ...,  64.,  87.,  93.],
       [ 23., 179., 180., ..., 205., 209., 215.]])

In [103]:
my_data_labels = all_data[1:,:1]
my_data_labels

array([[ 3.],
       [ 6.],
       [ 2.],
       ...,
       [18.],
       [17.],
       [23.]])

In [104]:
# Removes the header row and the label column
my_data = np.delete(all_data,0,1)
my_data = np.delete(my_data,0,0)
print(np.shape(my_data))
my_data

(27455, 784)


array([[107., 118., 127., ..., 204., 203., 202.],
       [155., 157., 156., ..., 103., 135., 149.],
       [187., 188., 188., ..., 195., 194., 195.],
       ...,
       [174., 174., 174., ..., 202., 200., 200.],
       [177., 181., 184., ...,  64.,  87.,  93.],
       [179., 180., 180., ..., 205., 209., 215.]])

In [105]:
len(my_data)

27455

In [106]:
# # Make a 28x28 black square

# w, h = 28,28
# data = np.zeros((h, w, 255), dtype=np.uint8) 
# img = Image.fromarray(data, 'RGB')
# # img.show()

In [107]:
w, h = 28,28
data = np.zeros((h, w), dtype=np.uint8)

In [108]:
np.shape(data)

(28, 28)

In [109]:
# Fill a 28x28 array with relevant image information
# Reminder: my_data_labels = all_data[1:,:1]


for z in range(len(my_data)):
    carry = -1
    for i in range(28):
        for j in range(28):
            if (j==0): 
                carry = carry + 1
    #         print(carry*28 + j)
            data[i,j] = my_data[z][carry*28 + j]
    img = Image.fromarray(data)
    img.save('Dataset1/imgData/Train/'+str(int(my_data_labels[z]))+'/'+str(z)+'.png')
#     img.show()

In [40]:
img = Image.fromarray(data)
# img.save('my.png')
img.show()